from typing import TypedDict

DO_NOT_EDIT_HEADER = "# DO NOT EDIT: This file is generated by terraform-autogen. Update the autogen_config.json file to change the generated code."


class FieldsConfig(TypedDict, total=False):
    impl: list[str]  # Fields to implement
    always_allow: list[str]  # Fields that are always allowed, even if computed
    never_allow: list[str]  # Fields that are never allowed, due to support/deprecation issues


FIELDS_CONFIG: FieldsConfig = {}
