variables:
  DOCKER_IMAGE: registry.ddbuild.io/images/docker:20.10
  TERRAFORM_AUTOGEN_IMAGE: registry.ddbuild.io/ci/terraform-autogen:latest

stages:
  - ci-image
  - test
  - run


# ------------- CI IMAGES -------------
serverless-remote-instrumentation ci image:
  stage: ci-image
  image: $DOCKER_IMAGE
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - serverless-remote-instrumentation/**/*
      when: on_success
  when: manual
  variables:
    DOCKER_TARGET: registry.ddbuild.io/ci/serverless-remote-instrumentation:latest
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f serverless-remote-instrumentation/Dockerfile serverless-remote-instrumentation/

terraform-autogen-ci-image:
  stage: ci-image
  image: $DOCKER_IMAGE
  tags: ['arch:amd64']
  rules:
    - when: manual
      allow_failure: true
  when: manual
  script:
    - docker buildx build --platform linux/amd64 --tag "$TERRAFORM_AUTOGEN_IMAGE" -f terraform-autogen/Dockerfile ./terraform-autogen/ --push

datadog-cdk-constructs ci image:
  stage: ci-image
  image: $DOCKER_IMAGE
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - datadog-cdk-constructs/**/*
        - utilities/**/*
      when: on_success
  when: manual
  variables:
    DOCKER_TARGET: registry.ddbuild.io/ci/datadog-cdk-constructs:latest
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f datadog-cdk-constructs/Dockerfile ./

serverless-plugin-datadog ci image:
  stage: ci-image
  image: $DOCKER_IMAGE
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - serverless-plugin-datadog/Dockerfile
      when: on_success
  when: manual
  variables:
    DOCKER_TARGET: registry.ddbuild.io/ci/serverless-plugin-datadog:latest
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f serverless-plugin-datadog/Dockerfile serverless-plugin-datadog/

# ------------- Testing/Validation -------------
terraform-autogen-lint:
  image: $TERRAFORM_AUTOGEN_IMAGE
  stage: test
  tags: ['arch:amd64']
  script:
    - cd terraform-autogen
    - ruff check

terraform-autogen-format:
  image: $TERRAFORM_AUTOGEN_IMAGE
  stage: test
  tags: ['arch:amd64']
  script:
    - cd terraform-autogen
    - ruff format --diff

terraform-autogen-typecheck:
  image: $TERRAFORM_AUTOGEN_IMAGE
  stage: test
  tags: ['arch:amd64']
  script:
    - cd terraform-autogen
    - pyright

# ------------- Scheduled Jobs -------------
terraform-autogen-campaigner:
  image: $TERRAFORM_AUTOGEN_IMAGE
  stage: run
  tags: ['arch:amd64']
  rules:
    - if: '$RUN_TERRAFORM_AUTOGEN == "true"'
  script: campaigns --no-config start --config-file /terraform-autogen/campaigner_config.yaml
