stages: 
  - build
  - release

variables:
  DOCKER_TARGET_IMAGE: registry.ddbuild.io/ci/datadog-cloudformation-macro-ci
  DOCKER_TARGET_VERSION: latest
  # Default version for development builds
  # This will be overwritten by the tag version if it is a release.
  VERSION: dev
  SANDBOX_NAME: sandbox
  SANDBOX_EXTERNAL_ID_NAME: sandbox-publish-externalid
  SANDBOX_ROLE_TO_ASSUME: sandbox-layer-deployer
  SANDBOX_ACCOUNT: 425362996713
  PROD_NAME: prod
  PROD_EXTERNAL_ID_NAME: prod-publish-externalid
  PROD_ROLE_TO_ASSUME: dd-serverless-layer-deployer-role
  PROD_ACCOUNT: 464622532012
  BUCKET: datadog-cloudformation-template

ci image:
  stage: build
  image: registry.ddbuild.io/images/docker:20.10
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - ./serverless/Dockerfile
      when: on_success
  variables:
    DOCKER_TARGET: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f ./serverless/Dockerfile .
      

release macro:
  stage: release
  image: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  tags: ["arch:arm64"]
  before_script:
    - EXTERNAL_ID_NAME=${SANDBOX_EXTERNAL_ID_NAME} ROLE_TO_ASSUME=${SANDBOX_ROLE_TO_ASSUME} AWS_ACCOUNT=${SANDBOX_ACCOUNT} source ./serverless/tools/get_secrets.sh
  script:
    - ./serverless/release.sh ${BUCKET}
  after_script:
    echo "Done uploading the template, and here is the CloudFormation quick launch URL"
    echo "https://console.aws.amazon.com/cloudformation/home#/stacks/quickCreate?stackName=datadog-serverless-macro&templateURL=${TEMPLATE_URL}"

