/*
 * Unless explicitly stated otherwise all files in this repository are licensed
 * under the Apache License Version 2.0.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2026 Datadog, Inc.
 */

/*
 * DO NOT EDIT: This file is autogenerated.
 */

export const lambdaLayerCatalog = {
  defaultLayerVersions: {
    node: 142,
    python: 127,
    java: 27,
    dotnet: 25,
    ruby: 30,
    extension: 99,
  },
  runtimes: [
    { runtime: "dotnet6", runtimeType: "DOTNET", layerName: "dd-trace-dotnet" },
    { runtime: "dotnet8", runtimeType: "DOTNET", layerName: "dd-trace-dotnet" },
    { runtime: "dotnet10", runtimeType: "DOTNET", layerName: "dd-trace-dotnet" },
    { runtime: "nodejs12.x", runtimeType: "NODE", layerName: "Datadog-Node12-x" },
    { runtime: "nodejs14.x", runtimeType: "NODE", layerName: "Datadog-Node14-x" },
    { runtime: "nodejs16.x", runtimeType: "NODE", layerName: "Datadog-Node16-x" },
    { runtime: "nodejs18.x", runtimeType: "NODE", layerName: "Datadog-Node18-x" },
    { runtime: "nodejs20.x", runtimeType: "NODE", layerName: "Datadog-Node20-x" },
    { runtime: "nodejs22.x", runtimeType: "NODE", layerName: "Datadog-Node22-x" },
    { runtime: "nodejs24.x", runtimeType: "NODE", layerName: "Datadog-Node24-x" },
    { runtime: "python3.6", runtimeType: "PYTHON", layerName: "Datadog-Python36" },
    { runtime: "python3.7", runtimeType: "PYTHON", layerName: "Datadog-Python37" },
    { runtime: "python3.8", runtimeType: "PYTHON", layerName: "Datadog-Python38" },
    { runtime: "python3.9", runtimeType: "PYTHON", layerName: "Datadog-Python39" },
    { runtime: "python3.10", runtimeType: "PYTHON", layerName: "Datadog-Python310" },
    { runtime: "python3.11", runtimeType: "PYTHON", layerName: "Datadog-Python311" },
    { runtime: "python3.12", runtimeType: "PYTHON", layerName: "Datadog-Python312" },
    { runtime: "python3.13", runtimeType: "PYTHON", layerName: "Datadog-Python313" },
    { runtime: "python3.14", runtimeType: "PYTHON", layerName: "Datadog-Python314" },
    { runtime: "java8.al2", runtimeType: "JAVA", layerName: "dd-trace-java" },
    { runtime: "java11", runtimeType: "JAVA", layerName: "dd-trace-java" },
    { runtime: "java17", runtimeType: "JAVA", layerName: "dd-trace-java" },
    { runtime: "java21", runtimeType: "JAVA", layerName: "dd-trace-java" },
    { runtime: "java25", runtimeType: "JAVA", layerName: "dd-trace-java" },
    { runtime: "provided", runtimeType: "CUSTOM" },
    { runtime: "provided.al2", runtimeType: "CUSTOM" },
    { runtime: "provided.al2023", runtimeType: "CUSTOM" },
    { runtime: "ruby3.2", runtimeType: "RUBY" },
    { runtime: "ruby3.3", runtimeType: "RUBY" },
    { runtime: "ruby3.4", runtimeType: "RUBY" },
    { runtime: "ruby4.0", runtimeType: "RUBY" },
    { runtime: "ruby32", layerName: "Datadog-Ruby3-2" },
    { runtime: "ruby33", layerName: "Datadog-Ruby3-3" },
    { runtime: "ruby34", layerName: "Datadog-Ruby3-4" },
    { runtime: "ruby40", layerName: "Datadog-Ruby4-0" },
  ],
} as const;
