/*
 * Unless explicitly stated otherwise all files in this repository are licensed
 * under the Apache License Version 2.0.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2021 Datadog, Inc.
 */

/*
 * Default Datadog Lambda layer versions bundled with this construct. These are
 * used when a corresponding `*LayerVersion`/`*LayerArn` prop is not provided.
 *
 * This file is autogenerated and updated automatically on each release. Do not
 * edit by hand.
 */

export const DD_DEFAULT_NODE_LAYER_VERSION = 140;
export const DD_DEFAULT_PYTHON_LAYER_VERSION = 125;
export const DD_DEFAULT_JAVA_LAYER_VERSION = 27;
export const DD_DEFAULT_DOTNET_LAYER_VERSION = 25;
export const DD_DEFAULT_RUBY_LAYER_VERSION = 29;
export const DD_DEFAULT_EXTENSION_LAYER_VERSION = 98;
