/*
 * Unless explicitly stated otherwise all files in this repository are licensed
 * under the Apache License Version 2.0.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2026 Datadog, Inc.
 */

/*
 * Default Datadog Lambda layer versions bundled with this construct. These are
 * used when a corresponding `*LayerVersion`/`*LayerArn` prop is not provided.
 * Exposed as a class so the values are available in all jsii languages.
 *
 * DO NOT EDIT: This file is autogenerated.
 */

export class DatadogDefaultLayerVersions {
  public static readonly NODE = 140;
  public static readonly PYTHON = 125;
  public static readonly JAVA = 27;
  public static readonly DOTNET = 25;
  public static readonly RUBY = 29;
  public static readonly EXTENSION = 98;
}
