/*
 * Unless explicitly stated otherwise all files in this repository are licensed
 * under the Apache License Version 2.0.
 *
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2026 Datadog, Inc.
 */

/*
 * DO NOT EDIT: This file is autogenerated.
 */

export const layerRuntimeCatalog = [
  {
    runtime: "dotnet6",
    runtimeType: "DOTNET",
    layerNames: { x86_64: "dd-trace-dotnet", arm64: "dd-trace-dotnet-ARM" },
  },
  {
    runtime: "dotnet8",
    runtimeType: "DOTNET",
    layerNames: { x86_64: "dd-trace-dotnet", arm64: "dd-trace-dotnet-ARM" },
  },
  {
    runtime: "dotnet10",
    runtimeType: "DOTNET",
    layerNames: { x86_64: "dd-trace-dotnet", arm64: "dd-trace-dotnet-ARM" },
  },
  {
    runtime: "nodejs12.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node12-x", arm64: "Datadog-Node12-x-ARM" },
  },
  {
    runtime: "nodejs14.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node14-x", arm64: "Datadog-Node14-x-ARM" },
  },
  {
    runtime: "nodejs16.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node16-x", arm64: "Datadog-Node16-x-ARM" },
  },
  {
    runtime: "nodejs18.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node18-x", arm64: "Datadog-Node18-x-ARM" },
  },
  {
    runtime: "nodejs20.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node20-x", arm64: "Datadog-Node20-x-ARM" },
  },
  {
    runtime: "nodejs22.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node22-x", arm64: "Datadog-Node22-x-ARM" },
  },
  {
    runtime: "nodejs24.x",
    runtimeType: "NODE",
    layerNames: { x86_64: "Datadog-Node24-x", arm64: "Datadog-Node24-x-ARM" },
  },
  {
    runtime: "python3.6",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python36", arm64: "Datadog-Python36-ARM" },
  },
  {
    runtime: "python3.7",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python37", arm64: "Datadog-Python37-ARM" },
  },
  {
    runtime: "python3.8",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python38", arm64: "Datadog-Python38-ARM" },
  },
  {
    runtime: "python3.9",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python39", arm64: "Datadog-Python39-ARM" },
  },
  {
    runtime: "python3.10",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python310", arm64: "Datadog-Python310-ARM" },
  },
  {
    runtime: "python3.11",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python311", arm64: "Datadog-Python311-ARM" },
  },
  {
    runtime: "python3.12",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python312", arm64: "Datadog-Python312-ARM" },
  },
  {
    runtime: "python3.13",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python313", arm64: "Datadog-Python313-ARM" },
  },
  {
    runtime: "python3.14",
    runtimeType: "PYTHON",
    layerNames: { x86_64: "Datadog-Python314", arm64: "Datadog-Python314-ARM" },
  },
  { runtime: "java8.al2", runtimeType: "JAVA", layerNames: { x86_64: "dd-trace-java", arm64: "dd-trace-java-ARM" } },
  { runtime: "java11", runtimeType: "JAVA", layerNames: { x86_64: "dd-trace-java", arm64: "dd-trace-java-ARM" } },
  { runtime: "java17", runtimeType: "JAVA", layerNames: { x86_64: "dd-trace-java", arm64: "dd-trace-java-ARM" } },
  { runtime: "java21", runtimeType: "JAVA", layerNames: { x86_64: "dd-trace-java", arm64: "dd-trace-java-ARM" } },
  { runtime: "java25", runtimeType: "JAVA", layerNames: { x86_64: "dd-trace-java", arm64: "dd-trace-java-ARM" } },
  { runtime: "provided", runtimeType: "CUSTOM" },
  { runtime: "provided.al2", runtimeType: "CUSTOM" },
  { runtime: "provided.al2023", runtimeType: "CUSTOM" },
  { runtime: "ruby3.2", runtimeType: "RUBY" },
  { runtime: "ruby3.3", runtimeType: "RUBY" },
  { runtime: "ruby3.4", runtimeType: "RUBY" },
  { runtime: "ruby4.0", runtimeType: "RUBY" },
  { runtime: "ruby32", layerNames: { x86_64: "Datadog-Ruby3-2", arm64: "Datadog-Ruby3-2-ARM" } },
  { runtime: "ruby33", layerNames: { x86_64: "Datadog-Ruby3-3", arm64: "Datadog-Ruby3-3-ARM" } },
  { runtime: "ruby34", layerNames: { x86_64: "Datadog-Ruby3-4", arm64: "Datadog-Ruby3-4-ARM" } },
  { runtime: "ruby40", layerNames: { x86_64: "Datadog-Ruby4-0", arm64: "Datadog-Ruby4-0-ARM" } },
] as const;
